# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullName" : "sneha",
#     "email" : "sneha@yahoo.com",
#     "password" : "Sneha123@"
# }

# POST http://localhost:3000/signin 
# Content-Type: application/json

# {
#     "email" : "sneha@yahoo.com",
#     "password" : "Sneha123@"
# }

GET http://localhost:3000/get-upload-url 
